name: Build and Publish Docker

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      manual:
        description: 'Please type version. Ex:"v*"'
        required: true
        default: ""
      
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: scratch2ros-docker
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PASS }}

      - name: Get version from tag
        id: ver
        if: github.event.inputs.manual == ''
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Get version from input
        if: steps.ver.conclusion == 'skipped' && github.event.inputs.manual != ''
        run: echo "RELEASE_VERSION=${{github.event.inputs.manual}}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile

          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
